"""
doc_sync.py — Step 9
Automates the maintenance of SCRIPTS_INDEX.md by scanning the project
and extracting purpose/functionality from script headers.
"""

import os
import re
import logging
from pathlib import Path

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(levelname)-8s %(message)s")
log = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).parent.parent.parent
INDEX_FILE = PROJECT_ROOT / "SCRIPTS_INDEX.md"

def extract_metadata(file_path: Path) -> dict:
    """
    Extracts the purpose and functionality from a file's header.
    Looks for docstrings or early comments.
    """
    ext = file_path.suffix
    content = file_path.read_text(encoding="utf-8")
    
    purpose = "No purpose defined."
    functionality = "No functionality defined."
    
    if ext == ".py":
        # Look for module docstring
        match = re.search(r'"""(.*?)"""', content, re.DOTALL)
        if match:
            doc = match.group(1).split('\n')
            doc = [d.strip() for d in doc if d.strip()]
            if doc:
                purpose = doc[0].split("—")[-1].strip() if "—" in doc[0] else doc[0]
                if len(doc) > 1:
                    functionality = " ".join(doc[1:])
    
    elif ext == ".ps1":
        # Look for early comments
        lines = content.split('\n')
        for line in lines:
            if line.startswith("#"):
                purpose = line.replace("#", "").strip()
                break
    
    return {"purpose": purpose, "functionality": functionality}

def sync():
    log.info("Starting documentation sync...")
    
    scripts = []
    
    # Files to track (manual whitelist for precision)
    tracked_files = [
        "run_local.ps1",
        "generate_index.py",
        "test_api.py",
        "owui_index_generator/local_api.py",
        "owui_index_generator/collectors/community_scraper.py",
        "owui_index_generator/renderers/markdown.py",
        "owui_index_generator/schema/extension.py",
        "owui_index_generator/maintenance/doc_sync.py"
    ]
    
    for rel_path in tracked_files:
        fpath = PROJECT_ROOT / rel_path
        if fpath.exists():
            meta = extract_metadata(fpath)
            scripts.append({
                "name": rel_path,
                "purpose": meta["purpose"],
                "functionality": meta["functionality"]
            })
    
    # Generate the Markdown content
    header = """# 📜 Project Scripts Index

This file is AUTO-GENERATED by `owui_index_generator/maintenance/doc_sync.py`.
It tracks all key scripts and modules, documenting their purpose and functionality.

| Script / Module | Purpose | Functionality |
| :--- | :--- | :--- |
"""
    
    rows = []
    for s in scripts:
        row = f"| `{s['name']}` | **{s['purpose']}** | {s['functionality']} |"
        rows.append(row)
        
    footer = """
## Directory Structure Summary
- `owui_index_generator/`: Core package containing the logic.
- `data/`: Output directory for the generated index files (`OWUI_INDEX.md`, `owui_index.json`).
- `samples/`: Raw API samples used for development and debugging.
- `Projects/`: Documentation and Master Plan tracking.
"""
    
    full_content = header + "\n".join(rows) + footer
    
    INDEX_FILE.write_text(full_content, encoding="utf-8")
    log.info(f"Successfully updated {INDEX_FILE.name}")

if __name__ == "__main__":
    sync()
